name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Packages
        run: npm install

      - name: Clean Public Folder
        run: rm -rf public/*

      - name: Create Public Structure
        run: |
          mkdir -p public/css
          mkdir -p public/js

      - name: Copy HTML
        run: cp resources/index.html public/

      - name: Copy CSS
        run: cp resources/css/style.css public/css/

      - name: Obfuscate JavaScript
        run: |
          npx javascript-obfuscator resources/js/script.js \
          --output public/js/script.js \
          --compact true \
          --control-flow-flattening true \
          --self-defending true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public